spring:
  application:
    name: Guardian
  mvc:
    throw-exception-if-no-handler-found: true
logging:
  level:
    fr.orionbs.guardian: debug
    org.springframework.security: debug

server:
  port: 9001
